### ISSUE TITLE
Макет плывет при уменьшении размера экрана

### ISSUE THREAD

**Issue by kinda-neat** [Geksanit/Ui-Kit#17]
![flow](https://user-images.githubusercontent.com/27883524/35479286-25e28a04-0426-11e8-8b0f-9d3af20c6120.gif)

**Comment by kinda-neat** [comment]
Если что в гугле можно посмотреть как твой макет выглядит при популярных размерах экрана, думаю тебе пригодится :)
![phones](https://user-images.githubusercontent.com/27883524/35479328-0833d32c-0427-11e8-8a84-9f43b2c15b98.gif)

**Comment by Geksanit** [comment]
Вот, вроде всё исправил.
