### ISSUE TITLE
размер кнопки

### ISSUE THREAD

**Issue by Geksanit** [Geksanit/Ui-Kit#18]
Кто должен определять размер блока, сам блок или контейнер в котором он находится? Для Кнопки удобнее иметь стандартные размеры и менять их модификаторами button_size_small и т.п. Но в некоторых местах нужно иметь нестандартную ширину.

**Comment by Geksanit** [comment]
А без фиксированных размеров текст в кнопке не будет пропорционален размерам.

**Comment by kinda-neat** [comment]
С кнопкой можно и модификаторами справиться, но по идее блок должен занимать все место что ему предоставляют, а за это место как раз отвечает контейнер :)
