### ISSUE TITLE
Соблюдать DRY в шаблонах

### ISSUE THREAD

**Issue by Znack** [Geksanit/Ui-Kit#19]
```
    if options.checked
        input(checked type = "checkbox" class = "checkbox " + options.mix name = options.name value = options.value)
    else
        input(type = "checkbox" class = "checkbox " + options.mix name = options.name value = options.value)
```

тут можно использовать тернарник и не дублировать все остальные пропсы тупо из-за checked одного

**Comment by Geksanit** [comment]
Да, забыл что можно checked = "true" )

**Comment by Geksanit** [comment]
Сделал так.
`checked = options.checked ? true : false`
ВебШтром показал мне, что я - торомоз ) можно было и без тернарника ))))
`checked = !!options.checked`
