### ISSUE TITLE
pixelperfect и пиксели 

### ISSUE THREAD

**Issue by Burize** [Geksanit/Ui-Kit#6]
Так же как и в первом макете все значения нужно задавать через относительные переменные. + сейчас вообще общая структура верстки не совпадает по макету (даже близко к пиксель перфекту).

1) Нужно сверстать адаптивные элементы
2) сам макет тоже должен быть резиновым и для какого то размера окна совпадать с pixelperfect.

Сейчас есть захордкоженые размеры и flexbox =)

**Comment by Geksanit** [comment]
Перелопатил все пиксели, поправил положения компонентов для перфекта.
