### ISSUE TITLE
select

### ISSUE THREAD

**Issue by Burize** [Geksanit/Ui-Kit#8]
Можешь обяснить где обрабатывается клик нему? - там js файла в папке нет, и в стилях ничего нет ...

**Comment by Geksanit** [comment]
Клик не обрабатывается. Выпадающее меню - это работа тэга <select>. А что должно происходить при клике?

**Comment by Burize** [comment]
Оу, я менял ноутбук и тут по-другому выглядят все стандартные элементы ...

![image](https://user-images.githubusercontent.com/22253666/34870104-b2a7dab0-f7bb-11e7-9199-ac0defa4ace2.png)

Мда, никак не мог найти как ты его стилизовал)
